[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning", "setuptools"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
name = "quri-parts-pyscf"
version = "0.0.0"
description = "A plugin to use PySCF with QURI Parts"
license = "Apache-2.0"
authors = ["QURI Parts Authors <opensource@qunasys.com>"]
readme = "README.md"
repository = "https://github.com/QunaSys/quri-parts"
documentation = "https://quri-parts.qunasys.com"
keywords = ["quantum", "quantum computing"]
classifiers = [
    "Topic :: Scientific/Engineering :: Physics",
    "Typing :: Typed"
]
packages = [
    { include = "quri_parts" }
]

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[tool.poetry.dependencies]
python = "^3.9.8"
typing-extensions = "^4.1.1"
numpy = ">=1.22.0"
pyscf = "^2.3.0"
quri-parts-core = "*"
quri-parts-chem = "*"

[tool.poetry.group.dev.dependencies]
quri-parts-circuit = {path = "../circuit", develop = true}
quri-parts-core = {path = "../core", develop = true}
quri-parts-chem = {path = "../chem", develop = true}

pytest = "^7.0.1"
flake8 = "^4.0.1"
mypy = ">=0.950"
docformatter = "^1.4"
isort = "^5.10.1"
black = "^23.1.0"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
