name: Check all notebooks

on:
  pull_request:
    paths:
      - poetry.lock
      - pyproject.toml

jobs:
  execute-all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - name: Install JPEG dependencies for Pillow
      run: sudo apt-get update && sudo apt-get install -y libjpeg-dev

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry install

    - run: |
        for f in $(find quri_sdk_notebooks -mindepth 1 -type f -name *.ipynb)
        do
          if grep -Fxq $f .exclude
          then
            echo "Skipping execution of $f"
          else
            echo "Executing $f"
            poetry run jupyter execute --inplace --JupyterApp.log_level=50 $f
          fi
        done
    